config/routes.rb
Rhodnius::Application.routes.draw do
  root 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    post '/login' => 'devise/sessions#create'
    get '/register' => 'devise/registrations#new'
    delete '/logoff' => 'devise/sessions#destroy'
  end

  get '/en' => 'set_language#english', :as => :english
  get '/pt-BR' => 'set_language#portuguese', :as => :portuguese
  get '/es' => 'set_language#spanish', :as => :spanish
  get 'set_language/set_session_and_redirect'

  get '/about' => 'about#index', :as => :about
  get '/cameras' => 'cameras#index', :as => :cameras

  resources :cameras
  resources :comments

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    session[:id_camera] = params[:selected_cam_id] unless params[:selected_cam_id].blank?
    @current_camera = session[:id_camera] ? Camera.find(session[:id_camera]) : nil
    # todo: Montar o link com as câmeras por ip
    @current_cam_adress =  @current_camera && !@current_camera.full_url.blank? ? @current_camera.full_url : nil
    @comment = Comment.new
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_camera_panel.html.erb
<% if @current_camera %>
  <div class="slider-wrapper" id="camPanel">
    <h4><%= @current_camera.name %></h4>
    <div class="cam" style="opacity: 1;">
      <%= @current_cam_adress.html_safe %>
    </div>
    <p class="description">
      <b>Description:</b><br />
      <%= @current_camera.description %>
    </p>
  </div>
<% else %>
  <div class="slider-wrapper" id="camPanel">
    <h4><%= I18n.t('.index.no_camera') %></h4>
    <div class="cam">
      <h5><%= I18n.t('.index.no_camera_to_show') %></h5>
    </div>
    <p class="description">
      <b><%= I18n.t('.index.description') %>:</b><br />
      <%= I18n.t('.index.description_text') %>
    </p>
  </div>
<% end %>

app/views/home/_login.html.erb
<% if user_signed_in? %>
    <%= I18n.t('.hello') %> <%= current_user.name %>! [<%= link_to 'Logout', logoff_path, :method => :delete %>]
<% else %>
    <%= link_to t('devise.links.sign_in'), login_path, :class => 'ajax', style: 'margin-right: 10px;' %> <!-- | -->
    <%#= link_to t('devise.links.sign_up'), register_path, :class => 'ajax' %>
<% end %>

app/views/home/_menu.html.erb
<ul class="menu">
  <li><%= link_to I18n.t('.translation.home'), root_path %></li>
  <li><%= link_to I18n.t('.translation.title_about'), about_path %></li>
  <% if current_user && current_user.admin %>
      <li><%= link_to 'Cameras', cameras_path %></li>
      <li><%#= link_to 'Profile', edit_user_password_path %></li>
  <% elsif current_user %>
      <li><%#= link_to 'Profile', edit_user_password_path %></li>
  <% end %>
</ul>

app/views/home/_set_language.html.erb
<%
   locale = {:en => '/en', :'pt-BR' => '/pt-BR', :es => '/es'}
   initial_language = ''
   locale.each do |key, value|
     if key == I18n.locale
       initial_language = value
     end
   end
   options = { 'English' => english_path, 'Português' => portuguese_path, 'Español' => spanish_path }
%>
<%= select(:language, :value, options, {:selected => initial_language }) %>

app/views/home/index.html.erb
<style>
    .selectCam {
        text-decoration: none;
    }
    .selectCam img {
        width: 97px;
        height: 90px;
    }
    .selectCam:hover {
        background-color: transparent;
    }
</style>
<!--todo: Refatorar -->
<article class="grid_2">
  <div class="usual">
    <ul class="idTabs">
      <li><a href="#jquery"><%= I18n.t('.index.comment_tag') %></a></li>
      <li><a href="#official"><%= I18n.t('.index.camera_tag') %></a></li>
    </ul>
    <div id="jquery">
      <% if user_signed_in? %>
        <%= render 'comments/form' %>
      <% else %>
        <p class="border-bot"><%= I18n.t('.index.to_comment') %></p>
      <% end %>

      <% unless Comment.count.zero? %>
        <br />
        <% @current_camera.comment.each do |comment| %>
          <p class="border-bot" style="width: 98.5%; padding: 10px; color: #4A7023;">
            <label class="com" style="font-weight: bold; color: #000;"><%= I18n.t('.comments.label_user') %>: </label>
            <%= comment.user.name %>
            <br />
            <label class="com" style="font-weight: bold; color: #000;"><%= I18n.t('.comments.label_comment') %>: </label>
            <%= comment.comment %>
            <br />
            <span style="float: right; font-size: 9px;"><%= comment.created_at.strftime("posted on %b, %m %Y - %H:%M") %></span>
            <br />
          </p>
        <% end %>
      <% else %>
        <%= I18n.t('.index.no_comments') %>
      <% end %>
    </div>
    <div id="official">
      <% if Camera.count > 0 %>
        <% Camera.all.each do |cam| %>
          <%= link_to image_tag('../images/simple_cam_logo.png', :border => 0), root_path(:selected_cam_id => cam.id), :class => 'selectCam', :remote => true, :title => cam.name.capitalize %>
        <% end %>
      <% else %>
          <p class="border-bot"><%= I18n.t('.index.no_camera_to_show') %></p>
      <% end %>
    </div>
  </div>
</article>
<article class="grid_3">
    <h6><%= link_to 'Facebook Bug Brother Brazil', 'https://www.facebook.com/pages/Bug-brother-brazil/281987428656852?ref=hl', :target => '_blanck', title: "#{I18n.t('.index.like_us')}", class: 'facebook social_link' %></h6><br />
    <h6><%= link_to 'Twitter Bug Brother Brazil', 'https://twitter.com/BugBroBrazil', :target => '_blanck', title: "#{I18n.t('.index.follow_us')}", class: 'twitter social_link' %></h6><br />
    <h6><%= link_to 'YouTube Bug Brother Brazil', 'https://www.youtube.com/channel/UCchulX1wSkUgCKpDAOR-GVA', :target => '_blanck', title: "#{I18n.t('.index.our_channel')}", class: 'youtube social_link' %></h6><br />
</article>