config/routes.rb
Rhodnius::Application.routes.draw do
  root 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    post '/login' => 'devise/sessions#create'
    get '/register' => 'devise/registrations#new'
    delete '/logoff' => 'devise/sessions#destroy'
  end

  get '/en' => 'set_language#english', :as => :english
  get '/pt-BR' => 'set_language#portuguese', :as => :portuguese
  get '/es' => 'set_language#spanish', :as => :spanish
  get 'set_language/set_session_and_redirect'

  get '/about' => 'about#index', :as => :about
  get '/cameras' => 'cameras#index', :as => :cameras

  resources :cameras
  resources :comments

  

end

app/models/camera.rb
class Camera < ActiveRecord::Base
  has_many :comment

  validates_presence_of :description, :name
  validates :name, :uniqueness => true
  self.inheritance_column = nil
end

app/controllers/cameras_controller.rb
class CamerasController < ApplicationController
  before_action :set_type_combo_values, only: [:new, :create, :edit, :update]
  before_action :set_camera, only: [:show, :edit, :update, :destroy]

  # GET /cameras
  # GET /cameras.json
  def index
    @cameras = Camera.all
  end

  # GET /cameras/1
  # GET /cameras/1.json
  def show
  end

  # GET /cameras/new
  def new
    @camera = Camera.new
  end

  # GET /cameras/1/edit
  def edit
  end

  # POST /cameras
  # POST /cameras.json
  def create
    set_default_dimension!(camera_params[:full_url]) unless camera_params[:full_url].blank?
    @camera = Camera.new(camera_params)

    respond_to do |format|
      if @camera.save
        format.html { redirect_to @camera, notice: I18n.t('.cameras.notice_successfully_created') }
        format.json { render action: 'show', status: :created, location: @camera }
      else
        format.html { render action: 'new' }
        format.json { render json: @camera.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cameras/1
  # PATCH/PUT /cameras/1.json
  def update
    set_default_dimension!(camera_params[:full_url]) unless camera_params[:full_url].blank?

    respond_to do |format|
      if @camera.update(camera_params)
        format.html { redirect_to @camera, notice: I18n.t('.cameras.notice_successfully_updated') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @camera.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cameras/1
  # DELETE /cameras/1.json
  def destroy
    @camera.destroy
    respond_to do |format|
      format.html { redirect_to cameras_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_camera
      @camera = Camera.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def camera_params
      params.require(:camera).permit(:name, :host, :port, :camera_user, :camera_user_password, :description, :type, :full_url)
    end

  def set_type_combo_values
    @camera_types = %w(Câmera Internet)
  end

  def set_default_dimension!(full_url)
    full_url.gsub(full_url[8, 11], 'width="770"').gsub(full_url[20, 12], 'height="367"')
  end
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/views/cameras/_form.html.erb
<script>
  $(document).on('change', '#camera_type', function(event){
    if ($('#camera_type').val() === 'Internet'){
      $('#internet_state').css({'visibility': 'visible', 'display': 'inline-block'});
      $('#cam_state').css({'visibility': 'hidden', 'display': 'none'});
    }else{
      $('#internet_state').css({'visibility': 'hidden', 'display': 'none'});
      $('#cam_state').css({'visibility': 'visible', 'display': 'inline-block'});
    }
  });
//  $(document).on('change', '#type_value', function(event){
//    if ($('#type_value').val() === 'Internet'){
//      $('#internet_state').css({'visibility': 'visible', 'display': 'inline-block'});
//      $('#cam_state').css({'visibility': 'hidden', 'display': 'none'});
//    }else{
//      $('#internet_state').css({'visibility': 'hidden', 'display': 'none'});
//      $('#cam_state').css({'visibility': 'visible', 'display': 'inline-block'});
//    }
//  });

//  $(document).ready(function(){
//    alert(JSON.stringify($('camera_type')));
//    if ($('#type_value').val() === 'Internet'){
//      $('#internet_state').css({'visibility': 'visible', 'display': 'inline-block'});
//      $('#cam_state').css({'visibility': 'hidden', 'display': 'none'});
//    }else{
//      $('#internet_state').css({'visibility': 'hidden', 'display': 'none'});
//      $('#cam_state').css({'visibility': 'visible', 'display': 'inline-block'});
//    }
//  });
</script>

<div class="usual" style="margin-left: 0;">
  <%= form_for(@camera) do |f| %>
    <% if @camera.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@camera.errors.count, "error") %> prohibited this camera from being saved:</h2>

        <ul>
          <% @camera.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <p>
         Altere o tipo de acoro com suas necessidades, se o vídeo tem um link da internet como vídeos do YouTube por
         exemplo selecione o tipo Internet e forneça a URL do vídeo, caso seja um vídeo de uma câmera IP selecione o
         tipo Câmera e forneça os dados para acesso.
      </p>

      <br />

      <section>
        <article>
          <b><%= I18n.t('.cameras.label_name') %></b><br />
          <%= f.text_field :name %>
        </article>

        <article>
          <b><%= I18n.t('.cameras.label_type') %></b><br />
          <%#= f.select :type, :value, @camera_types %>
          <%= f.select :type, @camera_types.each { |p| p } %>
        </article>
      </section>

      <section id="internet_state">
        <article>
          <b><%= I18n.t('.cameras.label_full_url') %></b><br />
          <%= f.text_field :full_url, style: 'width: 415px;' %>
        </article>
      </section>

      <section id="cam_state">
        <section>
          <article>
            <b><%= I18n.t('.cameras.label_host') %></b><br>
            <%= f.text_field :host %>
          </article>

          <article>
            <b><%= I18n.t('.cameras.label_port') %></b><br>
            <%= f.text_field :port %>
          </article>
        </section>

        <section>
          <article>
            <b><%= I18n.t('.cameras.label_camera_user') %></b><br>
            <%= f.text_field :camera_user %>
          </article>

          <article>
            <b><%= I18n.t('.cameras.label_camera_password') %></b><br>
            <%= f.text_field :camera_user_password %>
          </article>
        </section>
      </section>

      <b><%= I18n.t('.cameras.lanel_description') %></b><br>
      <%= f.text_area :description, style: 'width: 415px; height: 80px;' %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/cameras/edit.html.erb
<h1><%= I18n.t('.cameras.title_editing') %></h1>

<%= render 'form' %>

<%= link_to I18n.t('.translation.link_to_show'), @camera %> |
<%= link_to I18n.t('.translation.link_to_back'), cameras_path %>

app/views/cameras/index.html.erb
<div class="about-page">
  <img src="../images/right-arrow-icon.png" class="mark" />
  <h3><%= I18n.t('.cameras.title_listing_cameras') %></h3>
  <hr class="line" />

  <table class="bugTable">
    <thead>
      <tr>
        <th><%= I18n.t('.cameras.label_name') %></th>
        <th><%= I18n.t('.cameras.label_type') %></th>
        <th><%= I18n.t('.cameras.label_host') %></th>
        <th><%= I18n.t('.cameras.label_port') %></th>
        <th><%= I18n.t('.cameras.label_camera_user') %></th>
        <th><%= I18n.t('.cameras.label_camera_password') %></th>
        <th><%= I18n.t('.cameras.label_full_url') %></th>
        <th><%= I18n.t('.cameras.lanel_description') %></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @cameras.each do |camera| %>
        <tr>
          <td><%= camera.name %></td>
          <td><%= camera.type.blank? ? '---'.html_safe : camera.type %></td>
          <td><%= camera.host.blank? ? '---'.html_safe : camera.host %></td>
          <td><%= camera.port.blank? ? '---'.html_safe : camera.port %></td>
          <td><%= camera.camera_user.blank? ? '---'.html_safe : camera.camera_user %></td>
          <td><%= camera.camera_user_password.blank? ? '---'.html_safe : camera.camera_user_password %></td>
          <td><%= camera.full_url.blank? ? '---'.html_safe : camera.full_url %></td>
          <td><%= camera.description %></td>
          <td><%= link_to I18n.t('.translation.link_to_show'), camera %></td>
          <td><%= link_to I18n.t('.translation.link_to_edit'), edit_camera_path(camera) %></td>
          <td><%= link_to I18n.t('.translation.link_to_destroy'), camera, method: :delete, data: { confirm: I18n.t('.translation.alert_destroy_confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to I18n.t('.cameras.link_to_new_camera'), new_camera_path %>
</div>

app/views/cameras/new.html.erb
<style>
  div input,
  form div select,
  div textarea {
    color: #A3BA46;
    padding: 5px;
    font-size: 15px;
    text-shadow: 0 1px 0 #fff;
    outline: none;
    background-color: white;
    background: -webkit-gradient(linear, left top, left bottombottom, from(#bcbcbe), to(#ffffff));
    background: -moz-linear-gradient(top,  #bcbcbe,  #ffffff);
    -webkit-border-radius: 3px;
    -moz-border-radius: 3px;
    border-radius: 3px;
    border: 1px solid #666;
    -webkit-box-shadow: 1px 1px 0 #efefef;
    -moz-box-shadow: 1px 1px 0 #efefef;
    box-shadow:  1px 1px 0 #efefef;
    display: block;
    margin-bottom: 15px;
  }
  div section {
    display: inline-block;
    width: 100%;
    margin-bottom: 10px;
  }
  div article {
    float: left;
    margin-right: 20px;
  }
  div.actions, div input[type="submit"] {
    margin: 0;
  }
  div.actions {
    min-height: 30px;
    padding-left: 252px;
    padding-bottom: 15px;
  }
  #internet_state {
      display: none;
      visibility: hidden;
  }
</style>
<div class="about-page">
  <img src="../images/right-arrow-icon.png" class="mark" />
  <h3><%= I18n.t('.cameras.title_new') %></h3>
  <hr class="line" />

  <%= render 'form' %>

  <%= link_to I18n.t('.translation.link_to_back'), cameras_path %>
</div>

app/views/cameras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= I18n.t('.cameras.label_name') %>:</strong>
  <%= @camera.name %>
</p>

<p>
  <strong><%= I18n.t('.cameras.label_host') %>:</strong>
  <%= @camera.host %>
</p>

<p>
  <strong><%= I18n.t('.cameras.label_port') %>:</strong>
  <%= @camera.port %>
</p>

<p>
  <strong><%= I18n.t('.cameras.label_camera_user') %>:</strong>
  <%= @camera.camera_user %>
</p>

<p>
  <strong><%= I18n.t('.cameras.label_camera_password') %>:</strong>
  <%= @camera.camera_user_password %>
</p>

<p>
  <strong><%= I18n.t('.cameras.lanel_description') %>:</strong>
  <%= @camera.description %>
</p>

<%= link_to I18n.t('.translation.link_to_edit'), edit_camera_path(@camera) %> |
<%= link_to I18n.t('.translation.link_to_back'), cameras_path %>